version: "2"

services:
  grafana:
    image: grafana/grafana:4.2.0
    container_name: "roammeet-grafana"
    ports:
      - "3000:3000"
    volumes:
      - grafana-logs-volume:/var/log/grafana
      - grafana-data-volume:/var/lib/grafana
    env_file:
      - grafana-variables.env
      - github-oauth.env

  prometheus:
    image: prom/prometheus:v1.5.2
    container_name: "roammeet-prom"
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"


  telegraf:
    image: telegraf:1.2.1
    container_name: "roammeet-telegraf"
    ports:
      - "9126:9126"
    volumes:
      - "./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  grafana-logs-volume:
  grafana-data-volume:
